### ISSUE TITLE
安装后 china.js 变为 China.js 导致测试找不到文件

### ISSUE THREAD

**Issue by chenjiandongx** [echarts-maps/echarts-countries-js#1]
![image](https://user-images.githubusercontent.com/19553554/36625813-cdd61438-1961-11e8-97e6-6f5b365fecee.png)

如下图

![image](https://user-images.githubusercontent.com/19553554/36625818-d5999e2e-1961-11e8-9413-ae6a77d93c27.png)

安装了最新的 V0.0.8 版本仍旧为 China.js 但 world.js 是正常的。

![image](https://user-images.githubusercontent.com/19553554/36625868-f3690416-1962-11e8-92db-679f6481e216.png)

![image](https://user-images.githubusercontent.com/19553554/36625877-0d44cd5c-1963-11e8-870e-dec5ff02cd21.png)

看 Github 上的文件确实正常的 china.js，一个猜测：是不是你没有清理缓存或者本地内容再打包，导致没有覆盖掉原先的文件？试试清楚所有缓存再重新打包试试？

**Comment by chfw** [comment]
0.0.8就是为了解决这个问题。请先 pip uninstall echarts-countries-pypkg 并保证它已经被卸载了 然后再装。 pip install echarts-countries-pypkg --no-cache-dir
