### ISSUE TITLE
Map of Tanzania

### ISSUE THREAD

**Issue by Casper901** [echarts-maps/echarts-countries-js#32]
The map information of Tanzania is Incomplete. Please check it.

**Comment by chfw** [comment]
old:

<img width="306" alt="Screenshot 2024-11-23 at 15 45 07" src="https://github.com/user-attachments/assets/30be4d66-5089-40fc-88db-d31a232d4538">

new:

<img width="302" alt="Screenshot 2024-11-23 at 15 45 23" src="https://github.com/user-attachments/assets/d1a4af37-8b2a-4169-8e2f-7ec178dc8fcf">
