### ISSUE TITLE
哥伦比亚地图是错误的

### ISSUE THREAD

**Issue by xinanwu** [echarts-maps/echarts-countries-js#33]
哥伦比亚地图是错误的，不完整，请修改它

**Comment by chfw** [comment]
old:

<img width="305" alt="Screenshot 2024-11-23 at 15 55 03" src="https://github.com/user-attachments/assets/3aa862e8-11d5-4e76-b4c6-7e7a9668008f">

new:

<img width="294" alt="Screenshot 2024-11-23 at 15 55 13" src="https://github.com/user-attachments/assets/eaa0e0c0-ad2d-4c72-983f-ce2eff919178">
