### ISSUE TITLE
地图无法下载

### ISSUE THREAD

**Issue by simpleET** [echarts-maps/echarts-countries-js#37]
![image](https://user-images.githubusercontent.com/25925990/212593567-1002a31c-07a2-4984-96e5-3aaa72c98aa8.png)

**Comment by chfw** [comment]
fixed. please try again

**Comment by simpleET** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
