### ISSUE TITLE
English

### ISSUE THREAD

**Issue by JohnCoene** [echarts-maps/echarts-countries-js#5]
Is there any chance we can find those in English?

**Comment by chfw** [comment]
For current version, the answer is No.

But it is possible to plan English names in next release.

I will need to modify how the map is registered with echarts. For now, only Chinese names are registered.

**Comment by JohnCoene** [comment]
Thanks! Using the Geojson from @pissang’s Starbucks project in the meantime

**Comment by chfw** [comment]
Would the provision of geojson instead of js solve your problem? As an alternative solution.

**Comment by JohnCoene** [comment]
Sorry for the late response, I got the geojsons. Thank you!
