### ISSUE TITLE
How to change label in Japan map?

### ISSUE THREAD

**Issue by vuthingoc** [echarts-maps/echarts-countries-js#7]
In Japan map," Tokyo" label is not the correct place. How to change the label in Japan map?

**Comment by vuthingoc** [comment]
chfw, Thanks for answers.

**Comment by chfw** [comment]
https://github.com/apache/incubator-echarts/issues/4379

Following above issue, it is possible to change its center point(cp).

**Comment by chfw** [comment]
And if you think the center point is applicable to all users, please feel free to submit a pull request.
