### ISSUE TITLE
世界地图"东半球版"有可能实现吗？

### ISSUE THREAD

**Issue by cndongle** [echarts-maps/echarts-countries-js#8]
请问东半球版的世界地图是否可以通过调整参数实现？即以东经150°（150° E）为“中央经线”，以西经30° （30° W）经线为图幅的左边经线和右边经线，太平洋在中间的显示方案。
       当前是显示“西半球版”世界地图，即以0°经线为“中央经线”，以西经180°经线为左边经线、以东经180°经线为右边经线。

**Comment by chfw** [comment]
我的知识能力还做不到。echarts 群里有人说会做这个。

**Comment by cndongle** [comment]
我们尝试对world的geoJson数据中，每个端点的x坐标（经度）做了整体偏移，目前只有30°W经线穿越的格陵兰岛还无法闭合，其他图形没问题。

`
const longitudeOffset = longitude => {
  return (longitude > -30.0 ? longitude - 150.0 : longitude + 210.0)
}
`

**Comment by chfw** [comment]
D3 画可以闭合。echarts 的话，需要 echarts 核心团队帮忙。

**Comment by cndongle** [comment]
> D3 画可以闭合。echarts 的话，需要 echarts 核心团队帮忙。

嗯，最后魔改了一下geojson，让跨30度的区域都断开了。 设计好隐藏格陵兰岛的接口以防万一，没有比错的强一些。

**Comment by chfw** [comment]
好像有了新进展，请看这个：https://github.com/apache/incubator-echarts/issues/3899
