### ISSUE TITLE
Incorrect map to Singapore 

### ISSUE THREAD

**Issue by Shwshank** [echarts-maps/echarts-countries-js#9]
The coordinates of the Singapore map is mention as 
"@@dbFVa\\\\`JXGfTrPHPOX@TXhNbU@ISWSiA[_@GcLkZUMMAqJMAIWQOJMKY@OGYFL\\WDYNDb" This is the wrong map as it can be seen on the attached screenshot. 
![Screenshot from 2019-09-27 15-09-02](https://user-images.githubusercontent.com/7690226/65759670-17c9d700-e139-11e9-8812-8028ad6220c0.png)

**Comment by chfw** [comment]
https://echarts-maps.github.io/echarts-countries-js/preview.html#新加坡
